### PR TITLE
add a php tag to the nextcloud container

### PR DESCRIPTION
**Pull request by szaimen**
Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Comment by juliushaertl** [comment]
Wouldn't it make sense to do all changes against the main repository and just push the tags to the releases one once releasing?

**Comment by juliushaertl** [comment]
But then you could also open this PR against the main repo or? Would make it a bit easier to only have one place for changes and everything on the releases is handled through the automated sync. But not a blocker of course :)

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
We also have that for app releases with a condition to only run them on the releases https://github.com/nextcloud/deck/blob/master/.github/workflows/appstore-build-publish.yml#L20 but fine with me :)

**Comment by szaimen** [comment]
> We also have that for app releases with a condition to only run them on the releases https://github.com/nextcloud/deck/blob/master/.github/workflows/appstore-build-publish.yml#L20 but fine with me :)

all right that would indeed be a possibility but having separate workflows in each repo is a bit easier to work with, imo :)

**Pull request merged**
